/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package intrepion.greeting.json.rpc.server.java.javalin;

import io.javalin.Javalin;

public class App {
    public static void main(String[] args) {
        var app = Javalin.create(/*config*/)
            .get("/", ctx -> ctx.result("Hello World"))
            .start(7070);
    }
}
